//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FaceTest.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.7.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("_")]
        public string tb_Path {
            get {
                return ((string)(this["tb_Path"]));
            }
            set {
                this["tb_Path"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://192.168.8.101:8090")]
        public string tb_Url {
            get {
                return ((string)(this["tb_Url"]));
            }
            set {
                this["tb_Url"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("123")]
        public string tb_Pass {
            get {
                return ((string)(this["tb_Pass"]));
            }
            set {
                this["tb_Pass"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://192.168.8.100:8091/VerifyHandler.ashx")]
        public string tb_CallBackVerifyUrl {
            get {
                return ((string)(this["tb_CallBackVerifyUrl"]));
            }
            set {
                this["tb_CallBackVerifyUrl"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://192.168.8.100:8091/Handler.ashx")]
        public string tb_CallBackUrl {
            get {
                return ((string)(this["tb_CallBackUrl"]));
            }
            set {
                this["tb_CallBackUrl"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://192.168.8.100:8091/GetUpdate.ashx")]
        public string bt_GetApkVersion {
            get {
                return ((string)(this["bt_GetApkVersion"]));
            }
            set {
                this["bt_GetApkVersion"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://192.168.8.100:8091/HeartBeat.ashx")]
        public string tb_DownApkUrl {
            get {
                return ((string)(this["tb_DownApkUrl"]));
            }
            set {
                this["tb_DownApkUrl"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("zhp")]
        public string tb_SetPassTime_UserId {
            get {
                return ((string)(this["tb_SetPassTime_UserId"]));
            }
            set {
                this["tb_SetPassTime_UserId"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("住宿生")]
        public string tb_SetPassTime_PassTimeName {
            get {
                return ((string)(this["tb_SetPassTime_PassTimeName"]));
            }
            set {
                this["tb_SetPassTime_PassTimeName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://192.168.8.100:8091/HeartBeat.ashx")]
        public string tb_HeartBeatUrl {
            get {
                return ((string)(this["tb_HeartBeatUrl"]));
            }
            set {
                this["tb_HeartBeatUrl"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("住宿生")]
        public string tb_DeletePassTimeName {
            get {
                return ((string)(this["tb_DeletePassTimeName"]));
            }
            set {
                this["tb_DeletePassTimeName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("zhp")]
        public string tb_PersonAddOrUpdate_PersonId {
            get {
                return ((string)(this["tb_PersonAddOrUpdate_PersonId"]));
            }
            set {
                this["tb_PersonAddOrUpdate_PersonId"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("张洪鹏")]
        public string tb_PersonAddOrUpdate_PersonName {
            get {
                return ((string)(this["tb_PersonAddOrUpdate_PersonName"]));
            }
            set {
                this["tb_PersonAddOrUpdate_PersonName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("zhp")]
        public string tb_PersonDelete_PersonId {
            get {
                return ((string)(this["tb_PersonDelete_PersonId"]));
            }
            set {
                this["tb_PersonDelete_PersonId"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1_1_0")]
        public string tb_PersonFind_PersonId {
            get {
                return ((string)(this["tb_PersonFind_PersonId"]));
            }
            set {
                this["tb_PersonFind_PersonId"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1_1_0")]
        public string tb_FaceDelete_FaceId {
            get {
                return ((string)(this["tb_FaceDelete_FaceId"]));
            }
            set {
                this["tb_FaceDelete_FaceId"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("zhp")]
        public string tb_FaceAddOrUpdate_PersonId {
            get {
                return ((string)(this["tb_FaceAddOrUpdate_PersonId"]));
            }
            set {
                this["tb_FaceAddOrUpdate_PersonId"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("zhp")]
        public string tb_FaceAddOrUpdate_PersonName {
            get {
                return ((string)(this["tb_FaceAddOrUpdate_PersonName"]));
            }
            set {
                this["tb_FaceAddOrUpdate_PersonName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1_1_0")]
        public string tb_FaceFind_FaceId {
            get {
                return ((string)(this["tb_FaceFind_FaceId"]));
            }
            set {
                this["tb_FaceFind_FaceId"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://192.168.8.100:8091/Handler_His.ashx")]
        public string tb_CallBackUrl_His {
            get {
                return ((string)(this["tb_CallBackUrl_His"]));
            }
            set {
                this["tb_CallBackUrl_His"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("_")]
        public string tb_SplitChar {
            get {
                return ((string)(this["tb_SplitChar"]));
            }
            set {
                this["tb_SplitChar"] = value;
            }
        }
    }
}
